


# platform :iOS, '9.0'

target 'PantsExtension' do

pod 'SDWebImage'

pod 'IQKeyboardManager'

pod "BlocksKit", "~> 2.2.5"

pod "AFNetworking", "~> 3.0"

#pod 'SVProgressHUD'

pod 'Toast', '~> 3.1.0'

#pod 'OpenSSL-Classic', '~> 1.0.1.j'

#pod 'AliPay', '~> 2.1.2'

#pod 'GTMBase64', '~> 1.0.0'

pod 'ViewUtils'





end
